apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-lvs-prod-thanos
  namespace: argocd
spec:
  project: paas-observability

  source:
    chart: thanos
    repoURL: https://gitlabmaster-03.bo3.e-dialog.com/zks/cockpit/argocd/lgtm.git 
    targetRevision: main            # ← updated version
    helm:
      valuesFiles:
        - values.yaml                   # ← ArgoCD reads this from your git repo

  destination:
    server: https://10.118.174.129:6443
    namespace: lgtm-lvs-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m